#!/bin/bash

index="slack"
type="message"

# curl -XDELETE http://localhost:9200/$index
# curl -XPUT localhost:9200/$index
# curl -XPUT localhost:9200/$index/$type/_mapping -d '
# {
#     "message": {
#         "properties": {
#             "date": { "type": "date", "format": "basic_date_time_no_millis" },
#             "team": {"type": "string", "index": "not_analyzed"},
#             "channel": {"type": "string", "index": "not_analyzed"},
#             "username": {"type": "string", "index": "not_analyzed"}
#         }
#     }
# }
# '

./slack_json_logger $1 |
 while read line
  do
    id=$(echo $line | jq -c '.ts' | tr -d "\n")
    echo -e "{ \"index\" : { \"_index\" : \"slack\", \"_type\" : \"message\", \"_id\" : ${id}} }\n$line" |
      curl -XPOST localhost:9200/_bulk --data-binary @-
  done
